//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Banka()
        {
            this.Banka_Muduru = new HashSet<Banka_Muduru>();
        }
    
        public int banka_id { get; set; }
        public int durum_id { get; set; }
        public string banka_tel { get; set; }
        public string banka_adresi { get; set; }
        public string banka_eposta { get; set; }
    
        public virtual Banka_Toplam Banka_Toplam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Banka_Muduru> Banka_Muduru { get; set; }
    }
}
