//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banka_Muduru
    {
        public int banka_id { get; set; }
        public string mudur_adi { get; set; }
        public string mudur_soyadi { get; set; }
        public string mudur_Tc { get; set; }
        public string mudur_Tel { get; set; }
        public string mudur_Adres { get; set; }
        public string mudur_Eposta { get; set; }
        public string mudur_sifre { get; set; }
    
        public virtual Banka Banka { get; set; }
    }
}
