//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hesaplar
    {
        public int hesap_id { get; set; }
        public string hesap_turu { get; set; }
        public string hesap_bakiye { get; set; }
        public string musteri_Tc { get; set; }
    
        public virtual Musteri Musteri { get; set; }
    }
}
