//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class İslemler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public İslemler()
        {
            this.Makbuz = new HashSet<Makbuz>();
        }
    
        public int islem_id { get; set; }
        public string islem_adi { get; set; }
        public string islem_bakiye { get; set; }
        public string islem_tarihi { get; set; }
        public string musteri_Tc { get; set; }
        public string temsilci_Tc { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual Musteri_Temsilcisi Musteri_Temsilcisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Makbuz> Makbuz { get; set; }
    }
}
