//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanıcılar
    {
        public string Tc { get; set; }
        public string Adı_Soyadı { get; set; }
        public string sifre { get; set; }
        public string tip { get; set; }
    }
}
