//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Makbuz
    {
        public int makbuz_id { get; set; }
        public int islem_id { get; set; }
        public string makbuz_islemi { get; set; }
        public string makbuz_ucreti { get; set; }
    
        public virtual İslemler İslemler { get; set; }
    }
}
