//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteri()
        {
            this.Hesaplar = new HashSet<Hesaplar>();
            this.İslemler = new HashSet<İslemler>();
            this.Kredi_Borclari = new HashSet<Kredi_Borclari>();
        }
    
        public string musteri_adi { get; set; }
        public string musteri_soyadi { get; set; }
        public string musteri_adres { get; set; }
        public string musteri_Tc { get; set; }
        public string musteri_eposta { get; set; }
        public string musteri_tel { get; set; }
        public string musteri_sifre { get; set; }
        public string musteri_resmi { get; set; }
        public string temsilci_Tc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hesaplar> Hesaplar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<İslemler> İslemler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kredi_Borclari> Kredi_Borclari { get; set; }
        public virtual Musteri_Temsilcisi Musteri_Temsilcisi { get; set; }
    }
}
