//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri_Temsilcisi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteri_Temsilcisi()
        {
            this.İslemler = new HashSet<İslemler>();
            this.Musteri = new HashSet<Musteri>();
        }
    
        public string temsilci_adi { get; set; }
        public string temsilci_soyadi { get; set; }
        public string temsilci_adres { get; set; }
        public string temsilci_Tc { get; set; }
        public string temsilci_eposta { get; set; }
        public string temsilci_tel { get; set; }
        public string temsilci_sifre { get; set; }
        public string temsilci_resmi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<İslemler> İslemler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Musteri> Musteri { get; set; }
    }
}
